### ISSUE TITLE
Add configuration validation

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#18]
Validate the configuration on changes in the `ConfigurationCenter`. We should use utilities from Spring that should make this quite simple. Don't update nor fire the update event if the new configuration is not valid.

**Comment by ivansenic** [comment]
@JonasKunz is this fixed actually with #22?

**Comment by JonasKunz** [comment]
Yes, thought this was a part of #4 :D

**Comment by JonasKunz** [comment]
I think we forgot about one point which should be adressed here:
What happens if the startup configuration is invalid? Should the agent terminate or should it run with the default configuration? Or should we use some kind of "fail-safe" configuration where everything in the agent is disabled except for the polling for configuration changes?

**Comment by ivansenic** [comment]
Good point.. Let's tackle this case as well..
