### ISSUE TITLE
Setup project for the documentation

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#9]
As agreed we will keep the end-user documentation in the same repository as the code. This way we can:
* push documentation changes with code changes
* release the versioned documentation
* build the documentation at any time

As the scope of this ticket:
* setup a project for this (f.e. `inspectit-oce-documentation`)
* document everything that is important for the user until the time when the ticket is implemented

**Comment by mariusoe** [comment]
Let's checkout and evaluate whether https://docs.readthedocs.io/en/latest/builds.html can be used. Because the documentation will also build based on the code in Github using some plugins (Sphinx, MkDocs, doxygen, ...). If this is done, we also don't have to considere all the documentation-hosting, updating, ...

**Comment by mariusoe** [comment]
Another option, which looks quite promising, is https://asciidoctor.org/. It generates documentation based on markdown located in the repository and you can create references between the code and the documentation. This could be build using our CI tool and pushed to a server (webserver)
